/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class me_alex_s168_GPU */

#ifndef _Included_me_alex_s168_GPU
#define _Included_me_alex_s168_GPU
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     me_alex_s168_GPU
 * Method:    nStart
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_me_alex_1s168_GPU_nStart
  (JNIEnv *, jobject);

/*
 * Class:     me_alex_s168_GPU
 * Method:    nComuteCoresPerUnit
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_me_alex_1s168_GPU_nComuteCoresPerUnit
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     me_alex_s168_GPU
 * Method:    nCompueCores
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_me_alex_1s168_GPU_nCompueCores
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     me_alex_s168_GPU
 * Method:    nCircuitCompile
 * Signature: (JJJJJJJJJJJJ)J
 */
JNIEXPORT jlong JNICALL Java_me_alex_1s168_GPU_nCircuitCompile
  (JNIEnv *, jobject, jlong, jlong, jlong, jlong, jlong, jlong, jlong, jlong, jlong, jlong, jlong, jlong);

/*
 * Class:     me_alex_s168_GPU
 * Method:    nCircuitRun
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_me_alex_1s168_GPU_nCircuitRun
  (JNIEnv *, jobject, jlong);

/*
 * Class:     me_alex_s168_GPU
 * Method:    nCircuitFree
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_me_alex_1s168_GPU_nCircuitFree
  (JNIEnv *, jobject, jlong);

/*
 * Class:     me_alex_s168_GPU
 * Method:    nEnd
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_me_alex_1s168_GPU_nEnd
  (JNIEnv *, jobject);

JNIEXPORT jlong JNICALL Java_me_alex_1s168_GPU_nNumPlatforms (JNIEnv *, jobject);

JNIEXPORT jlong JNICALL Java_me_alex_1s168_GPU_nNumDevices (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
